app/coffee/MongoManager.coffee, app/coffee/MongoPackManager.coffee, app/coffee/PackManager.coffee, app/coffee/UpdatesManager.coffee, pack.coffee, package.json, test/unit/coffee/MongoManager/MongoManagerTests.coffee
Adds a 'pack' type which collects individual updates into a single mongo document, to reduce index size.
=> Use packs to reduce docHistory index size

app/coffee/MongoManager.coffee, app/coffee/UpdatesManager.coffee, test/unit/coffee/MongoManager/MongoManagerTests.coffee, test/unit/coffee/UpdatesManager/UpdatesManagerTests.coffee
This change replaces the popLastCompressedUpdate method with peekLastCompressedUpdate, so that the last compressed update is never deleted in mongo.  This prevents the op being lost if there is an unexpected failure while the update is in the popped state, or if there is a lock failure and two processes both pop the last update (causing two ops to be removed). 
If the last compressed update needs to be changed, it is now done in-place with mongo's findAndModify method (which is atomic)
=> modify last compressed op in place

app/coffee/RedisManager.coffee, app/coffee/UpdatesManager.coffee, test/unit/coffee/RedisManager/RedisManagerTests.coffee, test/unit/coffee/UpdatesManager/UpdatesManagerTests.coffee
This change makes the queued op deletion more robust in the event of an unexpected lock failure, by explicitly deleting only the ops which have been applied.
=> Only delete applied ops

app/coffee/DocArchiveManager.coffee, app/coffee/MongoAWS.coffee, app/coffee/MongoManager.coffee, app/coffee/UpdatesManager.coffee, test/acceptance/coffee/ArchivingUpdatesTests.coffee, test/unit/coffee/DocArchive/DocArchiveManager.coffee, test/unit/coffee/MongoManager/MongoManagerTests.coffee, test/unit/coffee/UpdatesManager/UpdatesManagerTests.coffee
When we archive a document history, send all the entries to S3 and record the status and last version in the docHistoryStats collection, instead of keeping the last op in the docHistory collection (since this ultimately leaves an op in docHistory for every project).
=> Archive all data in history

app/coffee/MongoManager.coffee, app/coffee/PackManager.coffee, app/coffee/UpdatesManager.coffee, test/acceptance/coffee/AppendingUpdatesTests.coffee, test/acceptance/coffee/ArchivingUpdatesTests.coffee, test/acceptance/coffee/FlushingUpdatesTests.coffee, test/unit/coffee/PackManager/PackManagerTests.coffee, test/unit/coffee/UpdatesManager/UpdatesManagerTests.coffee
Write all new docHistory ops into packs, to avoid filling mongo index with a lot of small objects.
=> Pack in place

app/coffee/UpdatesManager.coffee, app/coffee/WebApiManager.coffee, test/unit/coffee/UpdatesManager/UpdatesManagerTests.coffee
Prevent http timeouts from breaking the track changes lock.
Makes the http request to before the lock is taken, so that timeouts don't cause a problem.
=> move lock inside web http calls

app/coffee/HealthChecker.coffee, app/coffee/WebApiManager.coffee
now using requestretry module, which has a five second delay between retries. Need to increase the timeout on the health checks to allow for this, as the timeout is currently shorter than the retry delay.
=> update timeouts to allow for 5 second retry delay

app.coffee, app/coffee/HttpController.coffee, app/coffee/RedisManager.coffee, app/coffee/UpdatesManager.coffee
flush all the projects with keys in DocsWithHistoryOps:*  via the endpoint /check/all
also need to check for any remaining docs in UncompressedHistoryOps without an entry in DocsWithHistoryOps - adds a /check/dangling endpoint for this
does not work with redis cluster, only single redis - but we should only need this once for the migration.
=> simple flush for all projects

npm-shrinkwrap.json
shrinkwrap update changed mongodb-core version, causing "no primary available" errors
have added redis-sharelatex manually into shrinkwrap file to avoid changing any other versions
=> fix shrinkwrap

npm-shrinkwrap.json, package.json
manual edit to npm-shrinkwrap.json to preserve existing versions
=> update redis-sharelatex to v1.0.1

npm-shrinkwrap.json, package.json
updated shrinkwrap file entry for redis-sharelatex manually to avoid breaking other versions
=> update to redis-sharelatex v1.0.2

app.coffee, app/coffee/PackWorker.coffee
main changes are
- replace error with warning on archiving timeout
- only check packs for archiving once each week (avoid unnecessary work)
- log number of packs processed on timeout, for easier debugging of limits in future
=> make archiving less noisy

test/unit/coffee/UpdatesManager/UpdatesManagerTests.coffee
the behaviour of the code changed so that raw ops are always compressed
=> fix broken unit test

config/settings.defaults.coffee
Switches dev environment to use web_v2 container instead of web_sl container now that the SL container is not needed in most dev workflows.
Connects to sharelatex/sharelatex-dev-environment#121
=> Switch dev env to use v2 port instead of SL

package.json
using the same version as in web
not needed to get the tests to pass but maybe we should include it
=> add missing coffeescript to package.json

app.coffee, npm-shrinkwrap.json, package.json
Removes `v8-profiler` incompatible with node > 6, as per @henryoswald suggestion to get rid of the profiler over trying to fix with a different dependency.
Required for Overleaf Community/ Server Pro, that will be running in Node 10 in the next release.
No user functionality, Profiling only.
=> removed profiler

config/settings.defaults.coffee
Fix for `Tried to apply raw op at version X to last compressed update with version Y` errors.
This is handled by the existing continueOnError setting, which we used to have enabled but lost in the migration.  This PR adds the setting to the configuration file.
NA
https://github.com/overleaf/google-ops/pull/562
NA
Setting only
NA
NA
Sentry for "inconsistent doc versions" error
@henryoswald @jdleesmiller
=> add continueOnError in settings

app/coffee/RedisManager.coffee, test/unit/coffee/RedisManager/RedisManagerTests.coffee
Fix performance of removal of updates from queues with LREM as in https://github.com/overleaf/project-history/pull/287
NA
https://github.com/overleaf/project-history/issues/152
https://github.com/overleaf/issues/issues/2359
Small change, as previously mentioned by JLM in https://github.com/overleaf/project-history/pull/287#issuecomment-498371250 it could lead to different behaviour with duplicate entries in the queue (a situation which should not occur in theory).  So far this has not  caused any noticeable problems in project history.
Low
NA
NA
NA
We don't have metrics for track changes - we should add some basic ones.
@henryoswald  @jdleesmiller
=> fix performance of update removal

Dockerfile, Jenkinsfile, Makefile, app/coffee/MongoAWS.coffee, buildscript.txt, config/settings.defaults.coffee, docker-compose.ci.yml, docker-compose.yml, package.json, test/acceptance/coffee/ArchivingUpdatesTests.coffee, test/acceptance/coffee/helpers/TrackChangesApp.coffee, test/acceptance/coffee/helpers/TrackChangesClient.coffee
The acceptance tests depend on valid s3 credentials. Using AWS s3 for extensive testing costs $$ and slows down local development.
For the filestore project we are using a fake S3 docker container with great success.
This PR adds support for thirdparty S3 providers and uses the `adobe/s3mock` image for the acceptance tests.
Filestore PR that introduces the fake s3 container: https://github.com/overleaf/filestore/pull/58
Uses build-scripts from https://github.com/overleaf/dev-environment/pull/298
The added `AWS_CONFIG` entries in `app/coffee/MongoAWS.coffee` are equal to the aws-sdk defaults:
[`endpoint: undefined` ](https://github.com/aws/aws-sdk-js/blob/fb9e50e7d74bea4c79ccf72e0f585235771943a5/lib/config.js#L532)
[`s3ForcePathStyle: …
=> Add support for offline s3 tests

Dockerfile, Makefile, buildscript.txt, docker-compose.ci.yml, docker-compose.yml
Update the build scripts for https://github.com/overleaf/dev-environment/pull/294
This adds a new `base` stage for the docker image.
https://github.com/overleaf/dev-environment/pull/294
- `language=es`
The eslint rules changed in the build-scripts, which required some formatting
changes. These were automatically applied by `prettier-eslint --write`.
- `spelling`
An additional tweak was required to cleanup a pending task for the unit-tests.
- `filestore`,  `spelling` and `third-party-datastore`
See https://github.com/overleaf/dev-environment/pull/294#issuecomment-584777526
for details on the added `data-dir` parameter.
Low.
We will notice any complications in regards to starting the services in staging.
=> [misc] update the build scripts to 1.3.5

package-lock.json, package.json
Branched from https://github.com/overleaf/track-changes/pull/76 to make CI pass
Closes https://github.com/overleaf/track-changes/pull/76
----
Bumps [request](https://github.com/request/request) from 2.33.0 to 2.88.2.
- [Release notes](https://github.com/request/request/releases)
- [Changelog](https://github.com/request/request/blob/master/CHANGELOG.md)
- [Commits](https://github.com/request/request/commits)
Signed-off-by: dependabot[bot] <support@github.com>
=> Bump request from 2.33.0 to 2.88.2

docker-compose.ci.yml, docker-compose.yml
Fixes the problem of CI build being broken since June 11th 2020. A [newer image of `adobe/s3mock:2.1.21`](https://hub.docker.com/layers/adobe/s3mock/2.1.21/images/sha256-1bf8492f1e8d44297ed3b599713dab83de4d41beeff406cc21b636f808db8d36?context=explore) was pushed that day, causing the following error in `Archiving updates` acceptance tests:
```
One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag
```
Pinning the version, effectively rolling back to `2.1.20` fixes the build.
The only change introduced in `adobe/s3mock` is https://github.com/adobe/S3Mock/pull/224
Further investigation is required to understand the root cause, since `filestore` and `templates` services are using …
=> Pinned adobe/s3mock docker image

docker-compose.ci.yml, docker-compose.yml
The version of `adobe/s3mock` was pinned in https://github.com/overleaf/track-changes/pull/85 due to problems after `2.1.21` release.
The problem has been identified as a bug and fixed in `2.1.22` (see https://github.com/adobe/S3Mock/issues/223), so we're going back to the unpinned version.
Tests only
=> Removed pinned version of adobe/s3mock docker image

app/js/PackWorker.js, app/js/mongodb.js
Followup for https://github.com/overleaf/track-changes/pull/94
The PackWorker is like a script, but it lives in `app/js` and hence was not treated separately in regards to db handling. This PR is adding the missing `waitForDb` call and also adjusts the cleanup process. 
https://github.com/overleaf/issues/issues/2907
https://github.com/overleaf/track-changes/pull/94
High. Without the PackWorker the mongodb fills-up.
- start the service in the dev-env
- `$ curl -X POST 127.0.0.1:3015/pack`
- see reasonable output (previously the PackWorker crashed)
- `ready to exit from pack archive worker`
=> [PackWorker] fixes for the native mongo driver

app/js/LockManager.js, app/js/RedisManager.js, package-lock.json, package.json, test/acceptance/js/helpers/TrackChangesClient.js, test/unit/js/LockManager/LockManagerTests.js, test/unit/js/RedisManager/RedisManagerTests.js
For https://github.com/overleaf/issues/issues/3650
- removed support for redis-sentinel
- redis-wrapper was rewritten in plain ES and promisified
- mostly internal changes
- health check supports `await` natively
- `multi().exec()` supports `await` and unpacks the `ioredis` result
- package renamed as `@overleaf/redis-wrapper`
- requires changed imports
- added `peerDependency` of `@overleaf/o-error@3.1.0`
- requires an added/updated production dependency on o-error
- bring back support for redis-cluster
For https://github.com/overleaf/issues/issues/3650
https://github.com/overleaf/redis-wrapper/pull/16
High. The health check has been rewritten, so was the ioredis result unpacking.
- Health check: simulate redis failures (unavailable, corrupted read)
- I tested the services locally in …
=> [misc] bump @overleaf/redis-wrapper to version 2.0.0

app.js, app/js/HttpController.js, app/js/UpdatesManager.js, test/acceptance/js/ArchivingUpdatesTests.js, test/acceptance/js/ExportProjectTests.js, test/acceptance/js/helpers/TrackChangesClient.js
For https://github.com/overleaf/issues/issues/4023
This PR is adding a new endpoint for exporting all the updates and collaborators in a project.
For https://github.com/overleaf/issues/issues/4023
The streaming logic is complicating things a bit, but it safe-guards us from OOM crashing pods. Implementing a pagination API would complicate the export script. I added lots of comments that should explain every step.
Low. New endpoint.
- see added acceptance tests
- run export script on sharelatex history projects
=> [misc] add a new endpoint for exporting all the project history

app/js/HttpController.js, app/js/PackManager.js, app/js/ZipManager.js
The `HttpController.zipProject` endpoint will now wait for the zip archive to be written to disk before sending it, so that an appropriate error response can be sent instead if something goes wrong.
Promise rejections are now handled appropriately, so the response doesn't hang if there's an error.
`tempy` is added as a dependency, so it can handle creating the temporary file and cleaning it up at the end.
=> Write zip file to disk before sending
