overleaf/track-changes

app/coffee/MongoManager.coffee
app/coffee/PackManager.coffee
app/coffee/mongojs.coffee
pack.coffee

Improving the old packing script to become part of track changes

Move pack migration logic into PackManager

---

app.coffee
package.json

add the profiler to track-changes

add /profile endpoint

---

app/coffee/UpdatesManager.coffee
test/unit/coffee/UpdatesManager/UpdatesManagerTests.coffee

detect any out of order ops coming from docupdater

return error when out-of-order ops detected

---

app/coffee/LockManager.coffee
test/unit/coffee/LockManager/LockManagerTests.coffee

improve error handling of releaseLock

---

app/coffee/WebApiManager.coffee
npm-shrinkwrap.json
package.json
test/unit/coffee/WebApiManager/WebApiManagerTests.coffee

retry once after failed web api requests

use requestretry to work around web api timeouts

---

app/coffee/HttpController.coffee
app/coffee/UpdatesManager.coffee

support a limit on the number of projects flushed by track changes flushAll

allow limit on flushed projects

---

app/coffee/RedisManager.coffee

to allow flushing of all ops and check for dangling ops in cluster and single node redis

support scan operations on redis cluster

---

fixdangling.coffee

flush dangling docs

---

app/coffee/UpdatesManager.coffee

minimal change to log unparseable updates

log corrupt updates

---

app/coffee/MongoAWS.coffee

check for null bytes in JSON.stringify

null byte check for JSON.stringify in archiving

---

package.json

upgrade to ioredis 3 via redis-sharelatex

---

.travis.yml

See https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Specifying-Node.js-versions-using-.nvmrc

Make travis read node version from .nvmrc file

---

app/coffee/ProjectIterator.coffee

fixes broken unit tests.  Somehow these were interfering when included in the `PackManagerTests.coffee` file.

remove unnecessary modules

---

app/coffee/HttpController.coffee
test/unit/coffee/HttpController/HttpControllerTests.coffee

Same issue and fix as https://github.com/sharelatex/project-history-sharelatex/pull/267  but for projects on old history system.
NA
Connects to https://github.com/overleaf/sharelatex/issues/1517
Same changes as before
NA
NA
NA
@jdleesmiller @paulojreis

use explicit json content-type to avoid security issues with text/html

---

config/settings.defaults.coffee

Fixes web host lookup by applying the same check as in other services.
Should be backwards compatible

Fixed WEB_HOST lookup in settings

---

Dockerfile
docker-compose.yml

Use the locally built 10.18.1 image.
https://github.com/overleaf/issues/issues/2705

upgrade track-changes to local node:10.18.1 image

---

Dockerfile
docker-compose.yml

Upgrade to node:10.19.0, built from source. Will update to public node image when it becomes available

update to gcr.io/overleaf-ops/node:10.19.0

---

package-lock.json
package.json

This version fixes the HTTP request timing metrics, which were not
reporting correctly.
* https://github.com/overleaf/metrics-module/pull/29
Metrics

Upgrade metrics-sharelatex to 2.6.2

---

app.js

For https://github.com/overleaf/issues/issues/2965
I paired with @warncke on this.
https://github.com/overleaf/issues/issues/2965
High, but all usage should be covered by unit/acceptance tests.

[misc] fix express deprecations

---

package-lock.json
package.json

- Part of https://github.com/overleaf/issues/issues/3095
- High, if something goes wrong

Upgrade redis-sharelatex to 1.0.13

---

app/js/ZipManager.js

This adds a JSON manifest to the ZIP archive, for use when extracting data from the ZIP.

Add manifest to history zip
